basePath: /
definitions:
  dto.GenericResponseDTO:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  dto.GenericResponseWithDataDTO:
    properties:
      data: {}
      status:
        $ref: '#/definitions/dto.GenericResponseDTO'
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: FGA Digitalent Final Submission
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: MyGram API
  version: "1.0"
paths:
  /comment/:
    get:
      description: Get ALl Comment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseWithDataDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Get All Comment
      tags:
      - comment
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Create Comment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Create Comment
      tags:
      - comment
  /comment/:id:
    delete:
      description: Get Comment By Specific ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Delete Comment By Specific ID
      tags:
      - comment
    get:
      description: Get Comment By ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseWithDataDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Get Comment By ID
      tags:
      - comment
    put:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Update Comment By Specific ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Update Comment By Specific ID
      tags:
      - comment
  /photo/:
    get:
      description: Get ALl Photo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseWithDataDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Get All Photo
      tags:
      - photo
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Create Photo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Create Photo
      tags:
      - photo
  /photo/:id:
    delete:
      description: Get Photo By Specific ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Delete Photo By Specific ID
      tags:
      - comment
    get:
      description: Get Photo By ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseWithDataDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Get Photo By ID
      tags:
      - comment
    put:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Update Photo By Specific ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Update Photo By Specific ID
      tags:
      - comment
  /social/:
    get:
      description: Get All Social Media
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseWithDataDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Get All Social Media
      tags:
      - social_media
    post:
      description: Create Social Media and link it with User Account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Create Social Media
      tags:
      - social_media
  /social/:id:
    delete:
      description: Delete Social Media with specific ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Delete Social Media
      tags:
      - social_media
    get:
      description: Get Social Media with specific ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseWithDataDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Create Social Media
      tags:
      - social_media
    put:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Update Social Media with specific ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Update Social Media
      tags:
      - social_media
  /user/login:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Login with existing user account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Login User
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Register A User Account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponseDTO'
      summary: Register A User Account
      tags:
      - user
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
